### ISSUE TITLE
建议流式写入

### ISSUE THREAD

**Issue by lizhichao** [hisune/log2ck#1]
clickhouse 不建议小批量 高频率写入 ，需要你把数据攒到一起 到了一定的量一次性写入，对于日志监听这种实时写入 推荐使用流式写入 可以控制clickhouse 服务器产生文件碎片的频率 ，服务器压力小，写入性能也好，实时性也高

**Comment by hisune** [comment]
实际上现在是支持批量写入的，默认配置是单次写入100条，这个条数可以通过配置文件修改。

目前线上测试千万级别的数据写入量在默认配置的情况下暂时还看不到有对性能的影响，后面可以看情况做调整。

流式写入后面可以考虑，没有使用过这种方式。

**Comment by hisune** [comment]
@lizhichao 请教一下流式写入与相关clickhouse的文档吗？为什么他能控制clickhouse服务器产生文件碎片？

**Comment by lizhichao** [comment]
没有文档  ，这和ck的写入原理有关 , `one-ck`  已经支持

**Comment by lizhichao** [comment]
以前写了个类似的 `https://github.com/lizhichao/log2ck` 从标准输入获取信息 实时流式写入
